// Package grpc provides the gRPC server implementation for the translation service.
// It implements the interface generated from the proto so the gRPC runtime can route Translate RPCs to this code.
// It runs at runtime when the server process starts; it uses translator and optionally cache created in main.
package grpc

import (
	// context is used for cancellation and timeouts on each RPC so clients can cancel long-running translations.
	"context"

	// translationv1 is the package generated by protoc from api/proto/translation.proto.
	// It contains TranslateRequest, TranslateResponse, TranslationServiceServer, and RegisterTranslationServiceServer.
	translationv1 "github.com/ltduyhien/ai-lingua-go/api/gen/translation/v1"
	// translator is our Ollama-backed translator; we call it when the cache misses.

	// status and codes are used to turn errors (e.g. translator failure) into gRPC status codes so the client gets a proper error.
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Translator is the interface used by the server to perform translation; *translator.Translator satisfies it.
// We use an interface so tests can inject a mock without needing Ollama.
type Translator interface {
	Translate(ctx context.Context, text, sourceLang, targetLang string) (string, error)
}

// Cache is the interface used by the server to get and set cached translations; *cache.Cache satisfies it.
// We use an interface so tests can inject a mock without needing Redis. May be nil when Redis is disabled.
type Cache interface {
	Key(text, sourceLang, targetLang string) string
	Get(ctx context.Context, key string) (string, bool, error)
	Set(ctx context.Context, key, value string) error
}

// Server implements the TranslationService gRPC service defined in the proto.
type Server struct {
	translationv1.UnimplementedTranslationServiceServer
	translator Translator
	cache      Cache
}

// NewServer creates a gRPC server that uses the given translator and optionally the given cache.
// If c is nil, we skip cache lookups and stores and always call the translator.
func NewServer(tr Translator, c Cache) *Server {
	return &Server{translator: tr, cache: c}
}

// Translate is the RPC handler for the Translate method defined in the proto.
// The gRPC runtime decodes the incoming request into req and calls this; we return a response or a gRPC error.
func (s *Server) Translate(ctx context.Context, req *translationv1.TranslateRequest) (*translationv1.TranslateResponse, error) {
	// Validate that we have the required fields so we don't call the translator with empty input.
	if req.GetText() == "" {
		return nil, status.Error(codes.InvalidArgument, "text is required")
	}
	if req.GetSourceLang() == "" || req.GetTargetLang() == "" {
		return nil, status.Error(codes.InvalidArgument, "source_lang and target_lang are required")
	}
	// If cache is configured, try to get the translation from Redis first.
	if s.cache != nil {
		key := s.cache.Key(req.GetText(), req.GetSourceLang(), req.GetTargetLang())
		cached, ok, err := s.cache.Get(ctx, key)
		if err != nil {
			// Redis error; we don't fail the request, we fall through and translate (degraded mode).
			// Alternatively we could return status.Error(codes.Unavailable, err.Error()).
		} else if ok {
			// Cache hit; return the cached value so we don't call the LLM.
			return &translationv1.TranslateResponse{TranslatedText: cached}, nil
		}
		// Cache miss or no cache: call the translator.
		translated, err := s.translator.Translate(ctx, req.GetText(), req.GetSourceLang(), req.GetTargetLang())
		if err != nil {
			return nil, status.Errorf(codes.Internal, "translation failed: %v", err)
		}
		// Store in cache for next time; we ignore Set errors so a cache write failure doesn't fail the request.
		_ = s.cache.Set(ctx, key, translated)
		return &translationv1.TranslateResponse{TranslatedText: translated}, nil
	}
	// No cache: just translate and return.
	translated, err := s.translator.Translate(ctx, req.GetText(), req.GetSourceLang(), req.GetTargetLang())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "translation failed: %v", err)
	}
	return &translationv1.TranslateResponse{TranslatedText: translated}, nil
}
